[tool.poetry]
name = "comohay-api"
version = "1.0.0"
description = "API of [ComoHay](https://comohay.com) website implemented with [FastAPI](https://fastapi.tiangolo.com) and [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup)."
authors = ["leynier <leynier41@gmail.com>"]
homepage = "https://github.com/leynier/comohay-api"
repository = "https://github.com/leynier/comohay-api"
documentation = "https://github.com/leynier/comohay-api"
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
comohay-api = "api.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.4.0"
fastapi = {extras = ["all"], version = "^0.75.0"}
beautifulsoup4 = "^4.10.0"
aiohttp = {extras = ["speedups"], version = "^3.8.1"}

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
flake8 = "^4.0.1"
black = "^22.3"
isort = "^5.10.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
