[tool.poetry]
name = "comohay-api"
version = "1.0.0"
description = "API of [ComoHay](https://comohay.com) website implemented with [FastAPI](https://fastapi.tiangolo.com) and [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup)."
authors = ["leynier <leynier41@gmail.com>"]
homepage = "https://github.com/leynier/comohay-api"
repository = "https://github.com/leynier/comohay-api"
documentation = "https://github.com/leynier/comohay-api"
readme = "README.md"
license = "MIT"

[tool.poetry.scripts]
comohay-api = "comohay_api.main:app"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.3.2"
fastapi = {extras = ["all"], version = "^0.65.1"}
beautifulsoup4 = "^4.9.3"
aiohttp = {extras = ["speedups"], version = "^3.7.4"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
black = "^21.5b2"
isort = "^5.8.0"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
